### PR TITLE
Swift2 compatibility

### PR DESCRIPTION
**Pull request by mpclarkson**

### CODE REVIEW

**Comment by anderoonies** [comment]
:+1:

**Comment by SebastianOsinski** [comment]
Am I the only one who has errors in Xcode with this version? Xcode 7 beta 4 gives me multiple errors in HTTPsecurity.swift, e.g. 'SecPolicy does not have a member named takeRetainedValue', 'Cannot invoke 'takeRetainedValue' with no arguments'.

**Comment by anderoonies** [comment]
@SebastianOsinski i've built without any problems but i am in 7.0 beta still.

**Comment by mpclarkson** [comment]
It works in beta 3 but I haven't tested it in beta 4 yet - I only just downloaded it today. I'll update it in the next couple of days and submit another PR.

**Comment by SebastianOsinski** [comment]
Ok, thanks!

**Comment by mpclarkson** [comment]
@SebastianOsinski It's compiling now under beta4. Let me know if you have any issues.

**Comment by SebastianOsinski** [comment]
no issues at all, works great.

**Comment by daltoniam** [comment]
Hi all, I started on a Swift-2 branch that I would like some feedback on. I change the API to be more inline with Swift 2 and use exception handling, but let me know what you all think.
https://github.com/daltoniam/SwiftHTTP/tree/swift-2

**Comment by mpclarkson** [comment]
Looks good at a brief glance. I'll try and pull it into my current project when I get a chance... Seems like all I do at the moment is refactor Swift code. ;)

**Comment by daltoniam** [comment]
Thanks. Ha, I know what you mean. I got like 4 projects left to refactor to Swift 2. Starting to think I might not finish them before it goes full release :grin:.

**Comment by mpclarkson** [comment]
Wow, you changed a lot :) I'm going to have to hold off integrating this into my current project for a while, as I'll have to rewrite loads of code.

**Comment by daltoniam** [comment]
Makes sense. I debated on how much of an impact that might make. Once I started down the rabbit hole of adding exception handling, it felt like Swift 2.0 was going to force us to rewrite a lot regardless, so I just ended up refactor everything :smile: . We might want to merge your branch in like a Swift 2.0 compatibility branch so not to force everyone to change everything all at once.

**Comment by mpclarkson** [comment]
The changes certainly make sense but it's a massive BC break. I think it's a good idea to keep a compatibility branch and focus on the 'proper' swift 2 implementation.

**Comment by daltoniam** [comment]
@mpclarkson whenever you have a moment, could you please make your PR at this branch:

https://github.com/daltoniam/SwiftHTTP/tree/swift-2-bc

Also I really appreciate you helping out with SwiftHTTP and the transition to Swift 2.

**Comment by mpclarkson** [comment]
Done. New PR.

**Pull request closed without merging**
