### PR TITLE
adding multiple download support

### LINKED ISSUE #63: Multiple file downloads
I was tinkering with the library and I wanted to share, off the top of my head, my own implementation of multiple file downloads using multiple `downloadTasks` with the same background Session. Not sure if this is kosher though.

    public func downloadMultiple(urls: Array<String>, parameters: Dictionary<String,AnyObject>?,progress:((Double) -> Void)!, success:((HTTPResponse) -> Void)!, failure:((NSError, HTTPResponse?) -> Void)!) -> [String:NSURLSessionDownloadTask?] {
        
        var tasks = Dictionary<String,NSURLSessionDownloadTask>()
        let ident = createBackgroundIdent()
        let config = NSURLSessionConfiguration.backgroundSessionConfigurationWithIdentifier(ident)
        let session = NSURLSession(configuration: config, delegate: self, delegateQueue: nil)
        
        for url in urls {
            
            let serialReq = createRequest(url,method: .GET, parameters: parameters)
            if serialReq.error != nil {
                failure(serialReq.error!, nil)
                tasks[url] = nil
             }
            
            let task = session.downloadTaskWithRequest(serialReq.request)
            let taskId = ident + "-" + String(task.taskIdentifier)
            self.backgroundTaskMap[taskId] = BackgroundBlocks(success,failure,progress)
            task.resume()
            tasks[url] = task
        }
        
        return tasks
    }

Let me know what you think. I can put that into a pull request.

### PR DESCRIPTION
**Pull request by nawar**
I want to resolve #63 with this pull request. Please check and let me know. Please verify on a physical device.

### CODE REVIEW

**Comment by daltoniam** [comment]
Nice work. I like the idea of supporting multiple downloads. Some thoughts:

Would we want have a success or failure closure called on every download? I would assume the success closure would be called once all the downloads finished, else we could just call the `download()` method multiple times. We have to have the file move logic run on each download though, as the temp files get deleted rapidly after being downloaded.

Also could we remove the `NSLog` call :smile:

**Comment by nawar** [comment]
Good point :ok_hand:  
 I was testing with `didFinishDownloadToURL` and I noticed it is get called every time a `downloadTask` finishes downloading a file and it is where you pass the response to the `success` handler.
In that case, I just followed the normal flow of things by iOS, and I moved/saved each file once it finished downloading. Otherwise, we'd have to get a solution where we put all the cached files URLs together and process them later in the `success` call that would be called once, in that case, I am not sure if iOS will keep the cached files that long for them to be saved/moved later in the `success` call. Let me know if this sounds good :smile: 

Will remove the `NSLog` :stuck_out_tongue:

**Comment by daltoniam** [comment]
Yeah that makes sense. I think we should think a system where we can notify when all the downloads finish and then have a closure for moving/saving the files to the proper directory? 3 closures one for failed download, the other for movement/success and one for all of them finishing? At that point, I wonder if it might make sense to have something like a download manager that can have downloads scheduled to it, and notifies when all downloads finished? It could also save the download taskIds to disk so they can be revived in the case of the app closing.

**Comment by nawar** [comment]
I like the idea of a download manager and it makes more sense. It could be decoupled like 
`HTTPUpload.swift` and `HTTPTask.swift`. 

We can test the one-closure concept for success/failure with multiple downloads, it can work without any issues, the only part that worries me is how much time the cached files can live before being purged by the os, and what happens if the app crashes while downloading all these files and never get the chance to move them. Just my :thought_balloon:

**Comment by daltoniam** [comment]
Alright sounds good. I think you are correct on the one closure will be problematic. I was more meaning having the same success/failure closures, but just add an "all downloaded completed one". 

We could even go as far with the download manager to make its own repository as an extension/build off SwiftHTTP (like [Skeets](https://github.com/daltoniam/Skeets) is), depending on how complex/if it makes sense.

I have been kicking around creating an organization for SwiftHTTP/Skeets/Starscream, as they are all in the same vein of Swift networking. If we create the download manager, might make sense to create it and put it in there.

**Comment by nawar** [comment]
Well, you are the author, you call the shots :)
If you wish, just kick start the downloadManager repository and I'll
contribute to it.

**Pull request closed without merging**
