### PR TITLE
added HTTP method parameter to download method

### PR DESCRIPTION
**Pull request by claudiuvintila**

### CODE REVIEW

**Comment by daltoniam** [comment]
Interesting, I have never used any other HTTP method/verb other than GET. What other HTTPMethod are you using to need the change?

**Comment by claudiuvintila** [comment]
I use POST. I post some data to build a file and I don't want that data to be visible

**Comment by daltoniam** [comment]
ok cool. Can you make the `method` default parameter be .GET? I think something like so should work:
```swift
public func download(url: String, method: HTTPMethod = .GET, parameters: Dictionary<String,AnyObject>?,progress:((Double) -> Void)!, success:((HTTPResponse) -> Void)!, failure:((NSError, HTTPResponse?) -> Void)!) -> NSURLSessionDownloadTask?
```

That way any existing download calls will continue to work, but the new functionally is available.

**Comment by daltoniam** [comment]
I just added this in my latest checkin https://github.com/daltoniam/SwiftHTTP/commit/8559644b3239360fb3f70da8f1667dff17d8459f. Thanks for the PR.

**Comment by claudiuvintila** [comment]
Great! Sorry for that, I didn't have time till the weekend.

**Comment by daltoniam** [comment]
All good, I was in there making some changes and I figured I would just do it :smile:

**Pull request closed without merging**
