### PR TITLE
Encode url with UTF-8.

### PR DESCRIPTION
**Pull request by taug**

### CODE REVIEW

**Comment by daltoniam** [comment]
Most of the time, you shouldn't have to encoding the spaces in a URL as it is against the RFC spec (if memory serves correct). Does your URL look something like this?
```swift
http://domain.com/url.json?key=value with a space&someKey=somevalue
```
If so, that makes sense why NSURL was complaining. SwiftHTTP already handles parameters appending in the parameters argument:

```swift
var request = HTTPTask()
request.GET("http://domain.com/url.json", parameters: ["key": "value with a space", "someKey": "somevalue"], completionHandler: {(response: HTTPResponse) in
//do stuff
})
```

It automatically builds the parameters in the proper form to avoid having to manually append parameters to a url.

**Comment by taug** [comment]
My URL contains Chinese.

**Comment by daltoniam** [comment]
Right, but a URL can't contain spaces according to the RFC. I don't know Mandarin, so I am not sure if it follows something different. If you have an example url that would be helpful.

**Comment by daltoniam** [comment]
Are you able to share an example url or did you find a way to resolve it?

**Comment by taug** [comment]
Here is my url example:"http:domain.com/文件.mp3".

**Comment by taug** [comment]
And 
      urlVal.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!
solve my problem.

**Comment by daltoniam** [comment]
Ok cool. I just checked in a slightly safer version of the PR. Thanks for the report.

**Comment by taug** [comment]
Great

**Pull request closed without merging**
